#!/bin/bash
arg=$1

if [ -z "$arg" ]
then
	echo "No package name was entered, cancelling..."
	exit 0
fi

for pac in "$@"
do
	git clone https://aur.archlinux.org/$pac.git
	cd $pac
	makepkg -sic
	cd ..
	sudo rm -r $pac
done
